// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vuplumpkuaekgladkpmu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ1cGx1bXBrdWFla2dsYWRrcG11Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA5NjU1MjcsImV4cCI6MjA2NjU0MTUyN30.Jk3G3IeobDQ8xVKSYkEWJLgGNZc2QvwFrjGQ6Isgh2w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);